[2018-05-09 01:39:25,453] [INFO] "GET / HTTP/1.1" 200 19693
[2018-05-09 01:39:28,631] [INFO] "GET /gz/ HTTP/1.1" 302 0
[2018-05-09 01:39:28,882] [INFO] "GET /gz/login/?next=/gz/ HTTP/1.1" 200 3411
[2018-05-09 01:39:31,156] [INFO] "POST /gz/login/?next=/gz/ HTTP/1.1" 302 0
[2018-05-09 01:39:31,255] [INFO] "GET /gz/ HTTP/1.1" 200 21412
[2018-05-09 01:39:32,553] [ERROR] Internal Server Error: /gz/data_system/userinfo/
Traceback (most recent call last):
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'data_system_userinfo.switch' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 574, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1664, in changelist_view
    media = self.media + formset.media
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/forms/formsets.py", line 394, in media
    if self.forms:
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/forms/formsets.py", line 136, in forms
    for i in range(self.total_form_count())]
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/forms/formsets.py", line 112, in total_form_count
    initial_forms = self.initial_form_count()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/forms/models.py", line 574, in initial_form_count
    return len(self.get_queryset())
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1067, in execute_sql
    cursor.execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'data_system_userinfo.switch' in 'field list'")
[2018-05-09 01:39:32,560] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:39:33,015] [ERROR] "GET /gz/data_system/userinfo/ HTTP/1.1" 500 254855
[2018-05-09 01:40:38,797] [ERROR] Internal Server Error: /gz/data_system/userinfo/
Traceback (most recent call last):
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'data_system_userinfo.switch' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 574, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1664, in changelist_view
    media = self.media + formset.media
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/forms/formsets.py", line 394, in media
    if self.forms:
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/forms/formsets.py", line 136, in forms
    for i in range(self.total_form_count())]
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/forms/formsets.py", line 112, in total_form_count
    initial_forms = self.initial_form_count()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/forms/models.py", line 574, in initial_form_count
    return len(self.get_queryset())
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1067, in execute_sql
    cursor.execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/lambert/_project/_python/hongtu_record/venv/lib/python3.6/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1054, "Unknown column 'data_system_userinfo.switch' in 'field list'")
[2018-05-09 01:40:38,798] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:40:39,296] [ERROR] "GET /gz/data_system/userinfo/ HTTP/1.1" 500 254854
[2018-05-09 01:56:16,840] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 302 0
[2018-05-09 01:56:16,841] [INFO] "GET /gz/data_system/userinfo/ HTTP/1.1" 302 0
[2018-05-09 01:56:17,016] [INFO] "GET /gz/login/?next=/gz/data_system/userinfo/ HTTP/1.1" 200 3453
[2018-05-09 01:56:19,432] [INFO] "POST /gz/login/?next=/gz/data_system/userinfo/ HTTP/1.1" 302 0
[2018-05-09 01:56:19,685] [INFO] "GET /gz/data_system/userinfo/ HTTP/1.1" 200 22421
[2018-05-09 01:56:19,736] [INFO] "GET /gz/login/?next=/gz/jsi18n/ HTTP/1.1" 302 0
[2018-05-09 01:56:19,830] [INFO] "GET /gz/ HTTP/1.1" 200 21412
[2018-05-09 01:56:24,580] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:24,732] [INFO] "GET /gz/data_system/rechargerecords/ HTTP/1.1" 200 16755
[2018-05-09 01:56:25,808] [INFO] "GET /gz/data_system/telecomrealname/ HTTP/1.1" 200 24140
[2018-05-09 01:56:25,839] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:26,874] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:27,047] [INFO] "GET /gz/data_system/antifraudmiguan/ HTTP/1.1" 200 25433
[2018-05-09 01:56:27,835] [INFO] "GET /gz/data_system/financeinvestment/ HTTP/1.1" 200 19475
[2018-05-09 01:56:27,874] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:29,025] [INFO] "GET /gz/data_system/idcardrealnamemodel/ HTTP/1.1" 200 13116
[2018-05-09 01:56:29,065] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:30,196] [INFO] "GET /gz/data_system/idcardimgmodel/ HTTP/1.1" 200 17178
[2018-05-09 01:56:30,234] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:31,776] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:31,863] [INFO] "GET /gz/data_system/role/ HTTP/1.1" 200 13044
[2018-05-09 01:56:32,804] [INFO] "GET /gz/data_system/serviceinterface/ HTTP/1.1" 200 14939
[2018-05-09 01:56:34,304] [INFO] "GET /gz/examination/real_name/ HTTP/1.1" 200 19800
[2018-05-09 01:56:35,416] [INFO] "GET /gz/examination/enterprise/ HTTP/1.1" 200 18022
[2018-05-09 01:56:35,990] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:36,152] [INFO] "GET /gz/data_system/actionswitch/ HTTP/1.1" 200 15921
[2018-05-09 01:56:36,194] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:37,372] [INFO] "GET /gz/data_system/order/ HTTP/1.1" 200 23935
[2018-05-09 01:56:37,410] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:38,372] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:38,575] [INFO] "GET /gz/data_system/order/ HTTP/1.1" 200 23935
[2018-05-09 01:56:38,617] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:39,362] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:39,553] [INFO] "GET /gz/data_system/notice/ HTTP/1.1" 200 18452
[2018-05-09 01:56:39,589] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:56:41,509] [INFO] "GET /gz/data_system/minrechargeamount/ HTTP/1.1" 200 11581
[2018-05-09 01:56:41,553] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:57:32,713] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:57:32,907] [INFO] "GET /gz/data_system/minrechargeamount/ HTTP/1.1" 200 11928
[2018-05-09 01:57:34,531] [INFO] "GET /gz/data_system/minrechargeamount/add/ HTTP/1.1" 200 13440
[2018-05-09 01:57:34,579] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:57:37,072] [INFO] "POST /gz/data_system/minrechargeamount/add/ HTTP/1.1" 302 0
[2018-05-09 01:57:37,263] [INFO] "GET /gz/data_system/minrechargeamount/ HTTP/1.1" 200 13718
[2018-05-09 01:57:37,299] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:57:41,051] [INFO] "POST /gz/data_system/minrechargeamount/ HTTP/1.1" 302 0
[2018-05-09 01:57:41,228] [INFO] "GET /gz/data_system/minrechargeamount/ HTTP/1.1" 200 13644
[2018-05-09 01:57:41,299] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:57:46,830] [INFO] "GET /gz/jsi18n/ HTTP/1.1" 200 7717
[2018-05-09 01:57:47,028] [INFO] "GET /gz/data_system/minrechargeamount/ HTTP/1.1" 200 13126
